### ISSUE TITLE
Nodejs example crash

### ISSUE THREAD

**Issue by Yohannfra** [OnedocLabs/onedoc#1]
Hi,

I wanted to try your solution but the nodejs example of the documentation doesn't seems to work. 

I followed the getting started tutorial at https://app.onedoclabs.com/ and when I run it it crashes.

```index.js
const { Onedoc } = require("@onedoc/client");
const fs = require("fs");

const MY_API_KEY = "xxxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxx";

const onedoc = new Onedoc(MY_API_KEY);

(async () => {
  const { file, link, info, error } = await onedoc.render({
    html: "<h1>Hello, world!</h1>",
  });

  fs.writeFileSync("output.pdf", Buffer.from(file));
})();
```

The log I get:
```
$ npm run start

> test-onedoc@1.0.0 start
> node index.js


{
  uploadURL: 'https://xxxxxxxxxxxxxxxxxxxx.supabase.co/storage/v1/upload/resumable',
  username: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  password: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  bucket: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  signedUrls: [
    {
      signedUrl: 'https://xxxxxxxxxxxxxxxxxxxx.supabase.co/storage/v1/object/upload/sign/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/index.html?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      path: '/index.html',
      token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    }
  ]
}
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5329:19)
    at successSteps (node:internal/deps/undici/undici:5300:27)
    at fullyReadBody (node:internal/deps/undici/undici:1447:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:5309:7)
    at async Onedoc.render (/private/tmp/test-onedoc/node_modules/@onedoc/client/dist/index.js:196:17)
    at async /private/tmp/test-onedoc/index.js:7:39

Node.js v20.11.0

```

Am I doing anything wrong ?

Thanks,

Yohann

**Comment by pierredge** [comment]
Hey Yohann, yes, you are missing a few parameters, can you try with the following object?

```
let doc = {
    html: "<h1>Hello World</h1>",
    title: "Hello world",
    test: true,
    save: false,
    assets: [],
  };
```

Seems like the tutorial needs a little bit of an update, we will fix it, thanks for pointing out.

**Comment by Yohannfra** [comment]
Yes it works now thanks
